import hero_bg_img from "./hero_bg_img.png";
import default_restaurant_img from "./default_restaurant_Img.jpeg";
import membership_section_img from "./membership_section_img.png";
import {
    BeefIcon,
    Building2Icon,
    CroissantIcon,
    FishIcon,
    GlobeIcon,
    LeafIcon,
    MailIcon,
    Share2Icon,
    UtensilsCrossedIcon,
} from "lucide-react";

export const assets = {
    hero_bg_img,
    default_restaurant_img,
    membership_section_img,
};

export const dummyReviews = [
    {
        _id: "dummy-rev-1",
        userName: "Vaishali ",
        rating: 5,
        comment: "Absolutely amazing experience! The food was delicious, the service was excellent, and the atmosphere made our evening truly special. Highly recommended!",
        visitedDate: "2026-03-23T12:00:00.000Z",
        createdAt: "2026-03-23T12:00:00.000Z",
    },
    {
        _id: "dummy-rev-2",
        userName: "Annanya Methew",
        rating: 4,
        comment:
           "The food was delicious, especially the chef’s special dishes. The staff was friendly and attentive throughout our visit. We’ll definitely be coming back!",
        visitedDate: "2026-06-05T18:30:00.000Z",
        createdAt: "2026-04-08T18:30:00.000Z",
    },
    {
        _id: "dummy-rev-3",
        userName: "Aarti Mishra",
        rating: 5,
        comment: "Every dish was beautifully prepared and full of flavor. The meal exceeded our expectations and made for a truly memorable dining experience.",
        visitedDate: "2026-02-30T20:15:00.000Z",
        createdAt: "2026-02-30T20:15:00.000Z",
    },
];

export const dummyRating = 4.8;
export const dummyReviewCount = 124;

export const footerSections = [
    {
        title: "COMPANY",
        links: [
            { label: "About Us", path: "#" },
            { label: "Partner with Us", path: "#" },
            { label: "Careers", path: "#" },
        ],
    },
    {
        title: "LEGAL",
        links: [
            { label: "Terms of Service", path: "#" },
            { label: "Privacy Policy", path: "#" },
            { label: "Cookies", path: "#" },
        ],
    },
];

export const socialLinks = [
    { icon: GlobeIcon, href: "#" },
    { icon: Share2Icon, href: "#" },
    { icon: MailIcon, href: "#" },
];

export const bottomLinks = [
    { label: "Terms", path: "#" },
    { label: "Privacy", path: "#" },
];

export const cuisines = [
    { name: "Indian", icon: UtensilsCrossedIcon, label: "INDIAN" },
    { name: "Fish", icon: FishIcon, label: "Fish" },
    { name: "Momos", icon: CroissantIcon, label: "MOMOS" },
    { name: "Mithla", icon: Building2Icon, label: "MITHLA THALI" },
    { name: "Thakali", icon: BeefIcon, label: "THAKALI KHANA" },
    { name: "Vegetarian", icon: LeafIcon, label: "VEGETARIAN" },
];

export const dummyUser = {
    _id: "6a32a3c50e88c825d8873f75",
    name: "Ajit Sah",
    email: "sahajit0000@gmail.com",
    phone: "+01234567788",
    role: "owner",
    token: "xyz",
    createdAt: "2026-06-17T13:40:21.669Z",
    updatedAt: "2026-06-17T13:40:21.669Z",
};

export const dummyRestaurant = [
    {
        _id: "6a32a3c50e88c825d8873f7d",
        name: "Burger House",
        slug: "burger-house",
        description:
            "A stylish fine dining restaurant with elegant interiors, warm lighting, and a cozy atmosphere. Burger House offers beautifully presented dishes made with premium ingredients, blending modern flavors with timeless culinary traditions for a memorable dining experience.",
        cuisine: "Fast Food",
        priceRange: "₹₹₹",
        rating: 4.9,
        reviewCount: 88,
        location: "Kathmandu, Tinkune",
        address: "Tinkune,Kathmandu,Nepal",
        image: "/restaurant_5.png",
        chef: "Annanya Methew",
        tags: ["Romantic", "Velvet Booths", "Candlelit", "Haute Cuisine"],
        availableSlots: [,"18:00", "19:00", "20:00", "21:00", "22:00"],
        featured: true,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 45,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f7a",
        name: "Mithla Thali",
        slug: "mithla-thali",
        description:
            "A warm and elegant restaurant celebrating the rich flavors of Mithila cuisine. With traditional décor, soft lighting, and a welcoming atmosphere, Mithila Thali serves authentic regional dishes prepared with fresh ingredients and time-honored recipes. Every meal offers a true taste of Bihar’s cultural heritage, bringing families and food lovers together for a memorable dining experience",
        cuisine: "Thali",
        priceRange: "₹₹₹",
        rating: 4.7,
        reviewCount: 205,
        location: "Ramanad chowk,Janakpur",
        address: "Ramand chowk,Janakpur,Nepal",
        image: "/restaurant_3.jpg",
        chef: "Aarti Mishra",
        tags: ["Rooftop", "Skyline Views", "Handmade kHANA", "Craft Cocktails"],
        availableSlots: ["12:00", "13:00", "17:00", "18:00", "19:00", "20:00", "21:00"],
        featured: true,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 30,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f79",
        name: "Rajgharana Restaurant",
        slug: "rajgharana-restaurant",
        description:
            "A premium Indian restaurant offering an authentic dining experience inspired by India’s rich culinary traditions. Featuring elegant interiors, warm lighting, and a welcoming atmosphere, guests can enjoy freshly prepared dishes made with traditional recipes and high-quality ingredients. From flavorful North Indian curries and aromatic biryanis to sizzling tandoori specialties and regional favorites, every meal is crafted to deliver the true taste of India with exceptional hospitality.",
        cuisine: "Indian",
        priceRange: "₹₹₹₹",
        rating: 4.8,
        reviewCount: 92,
        location: "kathmandu,Nepal",
        address: "kathmandu,Nepal",
        image: "/restaurant_2.jpg",
        chef: "Rahul Sharma",
        tags: ["Omakase", "Basalt Counter", "Japanese", "Zen Atmosphere"],
        availableSlots: ["18:00", "20:30"],
        featured: true,
        exclusive: true,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 25,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f7c",
        name: "TULSI RESTAURANT",
        slug: "tulsi-restaurant",
        description:
            "A bright, airy conservatory celebrating organic, plant-forward gastronomy. Nestled under glass ceilings with floor-to-ceiling botanicals, Flora Garden transforms fresh seasonal crops into delicate, high-end editorial culinary works of art.",
        cuisine: "Vegetarian",
        priceRange: "₹₹₹",
        rating: 4.8,
        reviewCount: 110,
        location: "MUrli chowk,Janakpur",
        address: "Murli chowk,Janakpur,Nepal",
        image: "/restaurant_6.png",
        chef: "Vashaili",
        tags: ["Plant-Based", "Glasshouse", "Organic", "Bright & Airy"],
        availableSlots: ["11:30", "13:00", "14:30", "17:30", "19:00", "20:30"],
        featured: false,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 40,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f7b",
        name: "AJ CAFE",
        slug: "aj-cafe",
        description:
            "",
        cuisine: "Steakhouse",
        priceRange: "₹₹₹₹",
        rating: 4.6,
        reviewCount: 142,
        location: "Zeromile ,Janakpur",
        address: "Zeromile,Janakpur,Nepal",
        image: "/restaurant_1.png",
        chef: "Ajit Sah",
        tags: ["Dry-Aged Beef", "Wood Fire", "Moody Lighting", "Wine Room"],
        availableSlots: ["17:00", "18:00", "19:00", "20:00", "21:00", "22:00"],
        featured: false,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 35,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f78",
        name: "Dyalu Lord",
        slug: "dyalu-lord",
        description:
            "A premium hotel offering a perfect blend of modern comfort, elegant interiors, and exceptional hospitality. Designed with spacious rooms, stylish décor, and a relaxing atmosphere, the hotel provides a memorable stay for business travelers, families, and tourists alike. Guests can enjoy comfortable accommodations, delicious dining, modern amenities, and personalized service, making every visit relaxing, convenient, and truly enjoyable.",
        cuisine: "Hotel",
        priceRange: "₹₹₹₹",
        rating: 4.9,
        reviewCount: 124,
        location: "Birjung,NEPAL",
        address: " Ghanta ghar,Birjung ,NEPAL",
        image: "/restaurant_4.png",
        chef: "Jean-Pierre Dubois",
        tags: ["Michelin Star", "Fine Dining", "Tasting Menu", "Romantic"],
        availableSlots: ["17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30"],
        featured: true,
        exclusive: true,
        owner: "6a32a3c50e88c825d8873f77",
        status: "approved",
        totalSeats: 20,
        createdAt: "2026-06-17T13:40:21.827Z",
        updatedAt: "2026-06-17T13:40:21.827Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f7d",
        name: "Folsom Cafe",
        slug: "folsom-cafe",
        description:
            "A cozy and stylish café designed for relaxing moments, meaningful conversations, and great food. With elegant interiors, warm lighting, comfortable seating, and a welcoming atmosphere, it’s the perfect place to enjoy freshly brewed coffee, handcrafted beverages, delicious snacks, sandwiches, burgers, pizzas, pasta, and desserts. Every visit offers a comfortable setting, friendly service, and a memorable café experience for friends, families, and couples.",
        cuisine: "Cafe",
        priceRange: "₹₹₹₹",
        rating: 4.9,
        reviewCount: 88,
        location: "Biratnagar, Nepal",
        address: "Biratnagar, Nepal",
        image: "/restaurant_5.png",
        chef: "Ayushi Sharma",
        tags: ["Romantic", "Velvet Booths", "Candlelit", "Haute Cuisine", "momo",
        ],
        availableSlots: ["18:00", "19:00", "20:00", "21:00", "22:00"],
        featured: true,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "pending",
        totalSeats: 45,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
    {
        _id: "6a32a3c50e88c825d8873f7a",
        name: "Pariwar Restaurant",
        slug: "pariwar-restaurant",
        description:
            "A beautiful rooftop restaurant offering a relaxing atmosphere with elegant décor, lush greenery, and stunning city views. Guests can enjoy a wide variety of authentic Indian dishes, including flavorful curries, aromatic biryanis, freshly baked tandoori specialties, and delicious desserts. Prepared with fresh ingredients and traditional recipes, every meal is served with warm hospitality to create a memorable dining experience for families, friends, and special occasions.",
        cuisine: "Indian",
        priceRange: "₹₹₹",
        rating: 4.7,
        reviewCount: 205,
        location: "Kathmandu, Nepal",
        address: "Koteshwor, Kathmandu, Nepal",
        image: "/restaurant_3.jpg",
        chef: "Ajay Sah",
        tags: ["Rooftop", "Skyline Views", "Momo", "Handmade Pasta", "Craft Cocktails"],
        availableSlots: ["12:00", "13:00", "17:00", "18:00", "19:00", "20:00", "21:00"],
        featured: true,
        exclusive: false,
        owner: "6a32a3c50e88c825d8873f77",
        status: "pending",
        totalSeats: 30,
        createdAt: "2026-06-17T13:40:21.828Z",
        updatedAt: "2026-06-17T13:40:21.828Z",
    },
];

export const dummyAvailability = [
    { time: "18:00", availableSeats: 45, isAvailable: true },
    { time: "19:00", availableSeats: 45, isAvailable: true },
    { time: "20:00", availableSeats: 45, isAvailable: true },
    { time: "21:00", availableSeats: 45, isAvailable: true },
    { time: "22:00", availableSeats: 45, isAvailable: true },
];

export const dummyBookingData = {
    user: "6a32a3c50e88c825d8873f75",
    restaurant: {
        _id: "6a32a3c50e88c825d8873f7d",
        name: "L'Essence",
        location: "Manhattan, NY",
        address: "115 Greenwich St, New York, NY 10006",
        image: "/restaurant_5.png",
    },
    date: "2026-06-25T00:00:00.000Z",
    time: "22:00",
    guests: 2,
    occasion: "",
    specialRequests: "",
    status: "confirmed",
    _id: "6a34e4caf866d0ae1e98e487",
    createdAt: "2026-06-19T06:42:18.305Z",
    updatedAt: "2026-06-19T06:42:18.305Z",
    bookingId: "GR-71B448A7",
};

export const dummyMyBookingsData = [
    {
        _id: "6a34e4caf866d0ae1e98e487",
        user: "6a32a3c50e88c825d8873f75",
        restaurant: {
            _id: "6a32a3c50e88c825d8873f7d",
            name: "L'Essence",
            slug: "l-essence",
            location: "Manhattan, NY",
            address: "115 Greenwich St, New York, NY 10006",
            image: "/restaurant_5.png",
        },
        date: "2026-06-25T00:00:00.000Z",
        time: "22:00",
        guests: 2,
        occasion: "",
        specialRequests: "",
        status: "confirmed",
        createdAt: "2026-06-19T06:42:18.305Z",
        updatedAt: "2026-06-19T06:42:18.305Z",
        bookingId: "GR-71B448A7",
    },
    {
        _id: "6a34e55af866d0ae1e98e489",
        user: "6a32a3c50e88c825d8873f75",
        restaurant: {
            _id: "6a32a3c50e88c825d8873f7a",
            name: "Terraza Cielo",
            slug: "terraza-cielo",
            location: "Manhattan, NY",
            address: "244 Fifth Ave Rooftop, New York, NY 10001",
            image: "/restaurant_3.jpg",
        },
        date: "2026-06-19T00:00:00.000Z",
        time: "20:00",
        guests: 2,
        occasion: "",
        specialRequests: "",
        status: "confirmed",
        createdAt: "2026-06-19T06:44:42.294Z",
        updatedAt: "2026-06-19T06:44:42.294Z",
        bookingId: "GR-17743C76",
    },
    {
        _id: "6a34e54ff866d0ae1e98e488",
        user: "6a32a3c50e88c825d8873f75",
        restaurant: {
            _id: "6a32a3c50e88c825d8873f78",
            name: "L'Artiste",
            slug: "l-artiste",
            location: "Manhattan, NY",
            address: "420 Mercer St, New York, NY 10003",
            image: "/restaurant_4.png",
        },
        date: "2026-06-19T00:00:00.000Z",
        time: "19:00",
        guests: 2,
        occasion: "",
        specialRequests: "",
        status: "confirmed",
        createdAt: "2026-06-19T06:44:31.052Z",
        updatedAt: "2026-06-19T06:44:31.052Z",
        bookingId: "GR-F82DDD63",
    },
];

export const dummyAdminStats = {
    users: { totalUsers: 1, totalOwners: 1, total: 2 },
    restaurants: { total: 6 },
    bookings: { total: 1 },
    latestBookings: [
        {
            _id: "6a34f88580587be1dada87ba",
            user: { _id: "6a34ef24a4d96fc34d9c906b", name: "Marc Dubois", email: "owner@example.com" },
            restaurant: { _id: "6a34ef24a4d96fc34d9c906d", name: "Kuro Omakase" },
            date: "2026-06-19T00:00:00.000Z",
            time: "20:30",
            guests: 2,
            occasion: "",
            specialRequests: "",
            status: "confirmed",
            createdAt: "2026-06-19T08:06:29.155Z",
            updatedAt: "2026-06-19T08:06:29.155Z",
            bookingId: "GR-EB39904C",
        },
    ],
};

export const dummyFeaturedRestaurants = [dummyRestaurant[0], dummyRestaurant[1], dummyRestaurant[2]];
